server:
  port: 8080
  # servlet:
  #   context-path: /api
  webflux:
    base-path: /api

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://sg-devops.centralindia.cloudapp.azure.com/auth/realms/fitness-app/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://USERSERVICE
              predicates:
                - Path=/api/users/**
              filters:
                # - StripPrefix=1
                - PreserveHostHeader=true

            - id: activityservice
              uri: lb://ACTIVITYSERVICE
              predicates:
                - Path=/api/activities/**
              filters:
                # - StripPrefix=1
                - PreserveHostHeader=true

            - id: aiservice
              uri: lb://AISERVICE
              predicates:
                - Path=/api/recommendations/**
              filters:
                # - StripPrefix=1
                - PreserveHostHeader=true

# Naming Server
eureka:
  instance:
#    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG
#     reactor.netty.http.client: DEBUG
#     org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE