server:
  port: 8080
  # servlet:
  #   context-path: /api
  webflux:
    base-path: /api
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://sg-devops.centralindia.cloudapp.azure.com/auth/realms/fitness-app/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userservice
              uri: lb://USERSERVICE
              predicates:
                - Path=/api/users/**
              filters:
                # - StripPrefix=1
                - PreserveHostHeader=true

            - id: activityservice
              uri: lb://ACTIVITYSERVICE
              predicates:
                - Path=/api/activities/**
              filters:
                # - StripPrefix=1
                - PreserveHostHeader=true

            - id: aiservice
              uri: lb://AISERVICE
              predicates:
                - Path=/api/recommendations/**
              filters:
                # - StripPrefix=1
                - PreserveHostHeader=true

# Naming Server
eureka:
  instance:
#    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka

# OpenTelemetry Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for demo
  otlp:
    # tracing:
    #   endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
    metrics:
      export:
        enabled: true
        url: ${API_HOST}/observe/api/default/v1/metrics
        step: 30s     # export interval
        headers:
          Authorization: "Basic ${OTEL_EXPORTER_OTLP_AUTH_TOKEN}"
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${API_HOST}/observe/api/default/v1/traces
          headers:
            Authorization: "Basic ${OTEL_EXPORTER_OTLP_AUTH_TOKEN}"
    logging:
      export:
        otlp:
          endpoint: ${API_HOST}/observe/api/default/v1/logs
          headers:
            Authorization: "Basic ${OTEL_EXPORTER_OTLP_AUTH_TOKEN}"

# Logging with trace correlation
# logging:
#   pattern:
#     level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#   level:
#     root: INFO
#     com.sg.fitness: DEBUG
