spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://free-tier12.aws-ap-south-1.cockroachlabs.cloud:26257/swarna-db-200.testdb
    username: swarnadeep
    password: uLYrds69nT_WNO5vEQn9rQ

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

############### Swagger - openapi ###############
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs.html
#    operationsSorter: method
# Swagger path: http://localhost:8080/docs.html or http://localhost:8080/swagger-ui/index.html
