name: activityservice CI

on:
  # AUTO TRIGGER COMMENTED FOR NOW. UNCOMMENT WHEN READY TO ENABLE CI/CD automatically on push and pull request events.
  # push:
  #   branches:
  #     - main
  #     - master
  #   paths:
  #     - 'activityservice/**'
  #     - '.github/workflows/activityservice.yml'
  # pull_request:
  #   branches:
  #     - main
  #     - master
  #   paths:
  #     - 'activityservice/**'
  #     - '.github/workflows/activityservice.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      API_HOST: ${{ vars.API_HOST }}
      OTEL_EXPORTER_OTLP_AUTH_TOKEN: ${{ secrets.OTEL_EXPORTER_OTLP_AUTH_TOKEN }}

    steps:
      - name: SCM Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          cache-dependency-path: activityservice/pom.xml

      - name: Create Maven Settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>repsy</id>
                <username>${{ secrets.REPSY_USERNAME }}</username>
                <password>${{ secrets.REPSY_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # - name: Build
      #   working-directory: activityservice
      #   run: mvn -B clean package

      - name: Build and Push Artifact
        # if: ${{ secrets.REPSY_USERNAME != '' && secrets.REPSY_PASSWORD != '' }}
        working-directory: activityservice
        run: mvn -B clean deploy

      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: activityservice/target/site/jacoco/jacoco.xml
          format: jacoco
          base-path: activityservice
          flag-name: activityservice